config/routes.rb
Rails.application.routes.draw do
  resources :nudges
  resource :time_windows
  get 'nudges/:nudge_id/nudge', to: 'nudges#nudge', as: :send_nudge
  root 'nudges#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nudge.rb
class Nudge < ApplicationRecord
  #associations
  belongs_to :time_window

  #validations
  validates :title, :body, :time_window_id, presence: true
end

app/models/time_window.rb
class TimeWindow < ApplicationRecord
  #associations
  has_many :nudges

  #validations
  validates :name, :start_time, :end_time, presence: true
  validate :start_time_before_end_time

  #callbacks
  after_create :schedule_time_window_job

  def start_time_today
    (Date.today + start_time.hour.hours + start_time.min.minutes).to_datetime
  end

  def start_time_tomorrow
    (Date.tomorrow + start_time.hour.hours + start_time.min.minutes).to_datetime
  end

  def end_time_today
    (Date.today + end_time.hour.hours + end_time.min.minutes).to_datetime
  end

  def end_time_tomorrow
    (Date.tomorrow + end_time.hour.hours + end_time.min.minutes).to_datetime
  end

  def in_time_window?
    Time.current >= start_time_today && Time.current <= end_time_today
  end

  private

  def start_time_before_end_time
    return unless start_time && end_time

    if end_time <= start_time
      errors.add :end_time, 'End time must be after start time'
    end
  end

  def schedule_time_window_job
    TimeWindowJob.set(wait_until: start_time_to_schedule).perform_later(self.id)
  end

  def start_time_to_schedule
    if in_time_window?
      Time.current
    else
      start_time_tomorrow
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/nudges_controller.rb
class NudgesController < ApplicationController
  def index
    @nudges = Nudge.all
  end

  def new
    @nudge = Nudge.new
  end

  def create
    @nudge = Nudge.create(nudge_params)
    redirect_to nudges_path
  end

  def edit
    @nudge = Nudge.find(nudge_params[:id])
  end

  def update
    @nudge = Nudge.find(nudge_params[:id])
    @nudge.update(nudge_params)
  end

  def destroy
    @nudge = Nudge.find(params[:id])
    @nudge.destroy
    redirect_to nudges_path, notice: 'Nudge deleted'
  end

  def nudge
    NudgeJob.perform_later(params[:nudge_id])
    redirect_to nudges_path, notice: 'Nudged.'
  end

  private

  def nudge_params
    params.require(:nudge).permit(:id, :body, :title)
  end
end

app/controllers/time_windows_controller.rb
class TimeWindowsController < ApplicationController
  def index
    @time_windows = TimeWindow.all
  end

  def new
    @time_window = TimeWindow.new
  end

  def create
    TimewWindow.create(time_window_params)
  end

  private

  def time_window_params
    params.require(:time_window).permit(:id, :name, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nudge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/nudges/_nudge_form.erb
<%= simple_form_for @nudge do |form| %>
  <%= form.input :title %>
  <%= form.input :body %>
  <%= form.input :time_window_id, as: :select,  collection: TimeWindow.all.collect{ |t| [t.name, t.id] } %>
  <%= form.button :submit %>
<% end %>

app/views/nudges/index.erb
<div>
  <%= link_to 'Add new nudge', new_nudge_path %>
</div>

<div class='container'>
  <% @nudges.each do |nudge| %>
    <div class='row'>
      <h2><%= nudge.title %></h2>
      <p><%= nudge.body %></p>
      <%= link_to 'Nudge', send_nudge_path(nudge) %>
      <%= link_to 'Delete', nudge_path(nudge), method: :delete %>
    </div>
  <% end %>
</div>

app/views/nudges/new.erb
<h1>Create a new nudge</h1>
<%= render 'nudge_form' %>